language: node_js
node_js:
- '4.2'
sudo: true
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4
  main"
- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -qq -y clang-3.4
deploy:
  skip_cleanup: true
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: XumytS65w8l0mnWtrbjPAolKqwiscgQxpA43A5euWcPM6fqwEUcEqzqeAyzvCiARc4eL2hwIf2UgIGVXWkZIXgDynEcUqEtRTpSS/yOFAcu/N5jDj9LCvFynhooB8FuhxoTh1vTD/oQ42rNRDtMRRUa3FAf1kVrFKM+MUb1oyL0=
  on:
    tags: true
    repo: microflo/microflo-core
