language: node_js
node_js:
- '6'
sudo: false
dist: trusty
deploy:
  skip_cleanup: true
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: XumytS65w8l0mnWtrbjPAolKqwiscgQxpA43A5euWcPM6fqwEUcEqzqeAyzvCiARc4eL2hwIf2UgIGVXWkZIXgDynEcUqEtRTpSS/yOFAcu/N5jDj9LCvFynhooB8FuhxoTh1vTD/oQ42rNRDtMRRUa3FAf1kVrFKM+MUb1oyL0=
  on:
    tags: true
    repo: microflo/microflo-core
